/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AccountService_v1_9_0_AccountProviderTypes
 */
@JsonAdapter(AccountServiceV190AccountProviderTypes.Adapter.class)
public enum AccountServiceV190AccountProviderTypes {
  
  REDFISHSERVICE("RedfishService"),
  
  ACTIVEDIRECTORYSERVICE("ActiveDirectoryService"),
  
  LDAPSERVICE("LDAPService"),
  
  OEM("OEM"),
  
  TACACSPLUS("TACACSplus");

  private String value;

  AccountServiceV190AccountProviderTypes(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AccountServiceV190AccountProviderTypes fromValue(String value) {
    for (AccountServiceV190AccountProviderTypes b : AccountServiceV190AccountProviderTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AccountServiceV190AccountProviderTypes> {
    @Override
    public void write(final JsonWriter jsonWriter, final AccountServiceV190AccountProviderTypes enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AccountServiceV190AccountProviderTypes read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AccountServiceV190AccountProviderTypes.fromValue(value);
    }
  }
}

