/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This action is used to restore the boot order to the default state for the specified computer systems.
 */
@ApiModel(description = "This action is used to restore the boot order to the default state for the specified computer systems.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class AggregationServiceV101SetDefaultBootOrderRequestBody {
  public static final String SERIALIZED_NAME_SYSTEMS = "Systems";
  @SerializedName(SERIALIZED_NAME_SYSTEMS)
  private List<Object> systems = new ArrayList<Object>();


  public AggregationServiceV101SetDefaultBootOrderRequestBody systems(List<Object> systems) {
    
    this.systems = systems;
    return this;
  }

  public AggregationServiceV101SetDefaultBootOrderRequestBody addSystemsItem(Object systemsItem) {
    this.systems.add(systemsItem);
    return this;
  }

   /**
   * The computer systems to restore.
   * @return systems
  **/
  @ApiModelProperty(required = true, value = "The computer systems to restore.")

  public List<Object> getSystems() {
    return systems;
  }


  public void setSystems(List<Object> systems) {
    this.systems = systems;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggregationServiceV101SetDefaultBootOrderRequestBody aggregationServiceV101SetDefaultBootOrderRequestBody = (AggregationServiceV101SetDefaultBootOrderRequestBody) o;
    return Objects.equals(this.systems, aggregationServiceV101SetDefaultBootOrderRequestBody.systems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(systems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggregationServiceV101SetDefaultBootOrderRequestBody {\n");
    sb.append("    systems: ").append(toIndentedString(systems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

