/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The links to other resources that are related to this resource.
 */
@ApiModel(description = "The links to other resources that are related to this resource.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class AggregationSourceV110Links {
  public static final String SERIALIZED_NAME_CONNECTION_METHOD = "ConnectionMethod";
  @SerializedName(SERIALIZED_NAME_CONNECTION_METHOD)
  private Object connectionMethod = null;

  public static final String SERIALIZED_NAME_OEM = "Oem";
  @SerializedName(SERIALIZED_NAME_OEM)
  private Object oem = null;

  public static final String SERIALIZED_NAME_RESOURCES_ACCESSED = "ResourcesAccessed";
  @SerializedName(SERIALIZED_NAME_RESOURCES_ACCESSED)
  private List<Object> resourcesAccessed = null;

  public static final String SERIALIZED_NAME_RESOURCES_ACCESSED_AT_ODATA_COUNT = "ResourcesAccessed@odata.count";
  @SerializedName(SERIALIZED_NAME_RESOURCES_ACCESSED_AT_ODATA_COUNT)
  private Object resourcesAccessedAtOdataCount = null;


  public AggregationSourceV110Links connectionMethod(Object connectionMethod) {
    
    this.connectionMethod = connectionMethod;
    return this;
  }

   /**
   * Get connectionMethod
   * @return connectionMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getConnectionMethod() {
    return connectionMethod;
  }


  public void setConnectionMethod(Object connectionMethod) {
    this.connectionMethod = connectionMethod;
  }


  public AggregationSourceV110Links oem(Object oem) {
    
    this.oem = oem;
    return this;
  }

   /**
   * Get oem
   * @return oem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getOem() {
    return oem;
  }


  public void setOem(Object oem) {
    this.oem = oem;
  }


   /**
   * An array links to the resources added to the service through this aggregation source.  It is recommended that this be the minimal number of properties needed to find the resources that would be lost when the aggregation source is deleted.
   * @return resourcesAccessed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array links to the resources added to the service through this aggregation source.  It is recommended that this be the minimal number of properties needed to find the resources that would be lost when the aggregation source is deleted.")

  public List<Object> getResourcesAccessed() {
    return resourcesAccessed;
  }




  public AggregationSourceV110Links resourcesAccessedAtOdataCount(Object resourcesAccessedAtOdataCount) {
    
    this.resourcesAccessedAtOdataCount = resourcesAccessedAtOdataCount;
    return this;
  }

   /**
   * Get resourcesAccessedAtOdataCount
   * @return resourcesAccessedAtOdataCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getResourcesAccessedAtOdataCount() {
    return resourcesAccessedAtOdataCount;
  }


  public void setResourcesAccessedAtOdataCount(Object resourcesAccessedAtOdataCount) {
    this.resourcesAccessedAtOdataCount = resourcesAccessedAtOdataCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggregationSourceV110Links aggregationSourceV110Links = (AggregationSourceV110Links) o;
    return Objects.equals(this.connectionMethod, aggregationSourceV110Links.connectionMethod) &&
        Objects.equals(this.oem, aggregationSourceV110Links.oem) &&
        Objects.equals(this.resourcesAccessed, aggregationSourceV110Links.resourcesAccessed) &&
        Objects.equals(this.resourcesAccessedAtOdataCount, aggregationSourceV110Links.resourcesAccessedAtOdataCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectionMethod, oem, resourcesAccessed, resourcesAccessedAtOdataCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggregationSourceV110Links {\n");
    sb.append("    connectionMethod: ").append(toIndentedString(connectionMethod)).append("\n");
    sb.append("    oem: ").append(toIndentedString(oem)).append("\n");
    sb.append("    resourcesAccessed: ").append(toIndentedString(resourcesAccessed)).append("\n");
    sb.append("    resourcesAccessedAtOdataCount: ").append(toIndentedString(resourcesAccessedAtOdataCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

