/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * This action generates a certificate signing request by using the existing information and key-pair of the certificate.
 */
@ApiModel(description = "This action generates a certificate signing request by using the existing information and key-pair of the certificate.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class CertificateV130RenewRequestBody {
  public static final String SERIALIZED_NAME_CHALLENGE_PASSWORD = "ChallengePassword";
  @SerializedName(SERIALIZED_NAME_CHALLENGE_PASSWORD)
  private String challengePassword;


  public CertificateV130RenewRequestBody challengePassword(String challengePassword) {
    
    this.challengePassword = challengePassword;
    return this;
  }

   /**
   * The challenge password to apply to the certificate for revocation requests.
   * @return challengePassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The challenge password to apply to the certificate for revocation requests.")

  public String getChallengePassword() {
    return challengePassword;
  }


  public void setChallengePassword(String challengePassword) {
    this.challengePassword = challengePassword;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateV130RenewRequestBody certificateV130RenewRequestBody = (CertificateV130RenewRequestBody) o;
    return Objects.equals(this.challengePassword, certificateV130RenewRequestBody.challengePassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(challengePassword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateV130RenewRequestBody {\n");
    sb.append("    challengePassword: ").append(toIndentedString(challengePassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

