/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The available actions for this resource.
 */
@ApiModel(description = "The available actions for this resource.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class CertificateServiceV104Actions {
  public static final String SERIALIZED_NAME_HASH_CERTIFICATE_SERVICE_GENERATE_C_S_R = "#CertificateService.GenerateCSR";
  @SerializedName(SERIALIZED_NAME_HASH_CERTIFICATE_SERVICE_GENERATE_C_S_R)
  private Object hashCertificateServiceGenerateCSR = null;

  public static final String SERIALIZED_NAME_HASH_CERTIFICATE_SERVICE_REPLACE_CERTIFICATE = "#CertificateService.ReplaceCertificate";
  @SerializedName(SERIALIZED_NAME_HASH_CERTIFICATE_SERVICE_REPLACE_CERTIFICATE)
  private Object hashCertificateServiceReplaceCertificate = null;

  public static final String SERIALIZED_NAME_OEM = "Oem";
  @SerializedName(SERIALIZED_NAME_OEM)
  private Object oem = null;


  public CertificateServiceV104Actions hashCertificateServiceGenerateCSR(Object hashCertificateServiceGenerateCSR) {
    
    this.hashCertificateServiceGenerateCSR = hashCertificateServiceGenerateCSR;
    return this;
  }

   /**
   * Get hashCertificateServiceGenerateCSR
   * @return hashCertificateServiceGenerateCSR
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getHashCertificateServiceGenerateCSR() {
    return hashCertificateServiceGenerateCSR;
  }


  public void setHashCertificateServiceGenerateCSR(Object hashCertificateServiceGenerateCSR) {
    this.hashCertificateServiceGenerateCSR = hashCertificateServiceGenerateCSR;
  }


  public CertificateServiceV104Actions hashCertificateServiceReplaceCertificate(Object hashCertificateServiceReplaceCertificate) {
    
    this.hashCertificateServiceReplaceCertificate = hashCertificateServiceReplaceCertificate;
    return this;
  }

   /**
   * Get hashCertificateServiceReplaceCertificate
   * @return hashCertificateServiceReplaceCertificate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getHashCertificateServiceReplaceCertificate() {
    return hashCertificateServiceReplaceCertificate;
  }


  public void setHashCertificateServiceReplaceCertificate(Object hashCertificateServiceReplaceCertificate) {
    this.hashCertificateServiceReplaceCertificate = hashCertificateServiceReplaceCertificate;
  }


  public CertificateServiceV104Actions oem(Object oem) {
    
    this.oem = oem;
    return this;
  }

   /**
   * Get oem
   * @return oem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getOem() {
    return oem;
  }


  public void setOem(Object oem) {
    this.oem = oem;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateServiceV104Actions certificateServiceV104Actions = (CertificateServiceV104Actions) o;
    return Objects.equals(this.hashCertificateServiceGenerateCSR, certificateServiceV104Actions.hashCertificateServiceGenerateCSR) &&
        Objects.equals(this.hashCertificateServiceReplaceCertificate, certificateServiceV104Actions.hashCertificateServiceReplaceCertificate) &&
        Objects.equals(this.oem, certificateServiceV104Actions.oem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCertificateServiceGenerateCSR, hashCertificateServiceReplaceCertificate, oem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateServiceV104Actions {\n");
    sb.append("    hashCertificateServiceGenerateCSR: ").append(toIndentedString(hashCertificateServiceGenerateCSR)).append("\n");
    sb.append("    hashCertificateServiceReplaceCertificate: ").append(toIndentedString(hashCertificateServiceReplaceCertificate)).append("\n");
    sb.append("    oem: ").append(toIndentedString(oem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

