/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The available actions for this resource.
 */
@ApiModel(description = "The available actions for this resource.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class CertificateV130Actions {
  public static final String SERIALIZED_NAME_HASH_CERTIFICATE_REKEY = "#Certificate.Rekey";
  @SerializedName(SERIALIZED_NAME_HASH_CERTIFICATE_REKEY)
  private Object hashCertificateRekey = null;

  public static final String SERIALIZED_NAME_HASH_CERTIFICATE_RENEW = "#Certificate.Renew";
  @SerializedName(SERIALIZED_NAME_HASH_CERTIFICATE_RENEW)
  private Object hashCertificateRenew = null;

  public static final String SERIALIZED_NAME_OEM = "Oem";
  @SerializedName(SERIALIZED_NAME_OEM)
  private Object oem = null;


  public CertificateV130Actions hashCertificateRekey(Object hashCertificateRekey) {
    
    this.hashCertificateRekey = hashCertificateRekey;
    return this;
  }

   /**
   * Get hashCertificateRekey
   * @return hashCertificateRekey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getHashCertificateRekey() {
    return hashCertificateRekey;
  }


  public void setHashCertificateRekey(Object hashCertificateRekey) {
    this.hashCertificateRekey = hashCertificateRekey;
  }


  public CertificateV130Actions hashCertificateRenew(Object hashCertificateRenew) {
    
    this.hashCertificateRenew = hashCertificateRenew;
    return this;
  }

   /**
   * Get hashCertificateRenew
   * @return hashCertificateRenew
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getHashCertificateRenew() {
    return hashCertificateRenew;
  }


  public void setHashCertificateRenew(Object hashCertificateRenew) {
    this.hashCertificateRenew = hashCertificateRenew;
  }


  public CertificateV130Actions oem(Object oem) {
    
    this.oem = oem;
    return this;
  }

   /**
   * Get oem
   * @return oem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getOem() {
    return oem;
  }


  public void setOem(Object oem) {
    this.oem = oem;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateV130Actions certificateV130Actions = (CertificateV130Actions) o;
    return Objects.equals(this.hashCertificateRekey, certificateV130Actions.hashCertificateRekey) &&
        Objects.equals(this.hashCertificateRenew, certificateV130Actions.hashCertificateRenew) &&
        Objects.equals(this.oem, certificateV130Actions.oem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCertificateRekey, hashCertificateRenew, oem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateV130Actions {\n");
    sb.append("    hashCertificateRekey: ").append(toIndentedString(hashCertificateRekey)).append("\n");
    sb.append("    hashCertificateRenew: ").append(toIndentedString(hashCertificateRenew)).append("\n");
    sb.append("    oem: ").append(toIndentedString(oem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

