/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This action makes a certificate signing request.
 */
@ApiModel(description = "This action makes a certificate signing request.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class CertificateServiceV104GenerateCSRRequestBody {
  public static final String SERIALIZED_NAME_ALTERNATIVE_NAMES = "AlternativeNames";
  @SerializedName(SERIALIZED_NAME_ALTERNATIVE_NAMES)
  private List<String> alternativeNames = null;

  public static final String SERIALIZED_NAME_CERTIFICATE_COLLECTION = "CertificateCollection";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE_COLLECTION)
  private Object certificateCollection = null;

  public static final String SERIALIZED_NAME_CHALLENGE_PASSWORD = "ChallengePassword";
  @SerializedName(SERIALIZED_NAME_CHALLENGE_PASSWORD)
  private String challengePassword;

  public static final String SERIALIZED_NAME_CITY = "City";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_COMMON_NAME = "CommonName";
  @SerializedName(SERIALIZED_NAME_COMMON_NAME)
  private String commonName;

  public static final String SERIALIZED_NAME_CONTACT_PERSON = "ContactPerson";
  @SerializedName(SERIALIZED_NAME_CONTACT_PERSON)
  private String contactPerson;

  public static final String SERIALIZED_NAME_COUNTRY = "Country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_EMAIL = "Email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_GIVEN_NAME = "GivenName";
  @SerializedName(SERIALIZED_NAME_GIVEN_NAME)
  private String givenName;

  public static final String SERIALIZED_NAME_INITIALS = "Initials";
  @SerializedName(SERIALIZED_NAME_INITIALS)
  private String initials;

  public static final String SERIALIZED_NAME_KEY_BIT_LENGTH = "KeyBitLength";
  @SerializedName(SERIALIZED_NAME_KEY_BIT_LENGTH)
  private Long keyBitLength;

  public static final String SERIALIZED_NAME_KEY_CURVE_ID = "KeyCurveId";
  @SerializedName(SERIALIZED_NAME_KEY_CURVE_ID)
  private String keyCurveId;

  public static final String SERIALIZED_NAME_KEY_PAIR_ALGORITHM = "KeyPairAlgorithm";
  @SerializedName(SERIALIZED_NAME_KEY_PAIR_ALGORITHM)
  private String keyPairAlgorithm;

  public static final String SERIALIZED_NAME_KEY_USAGE = "KeyUsage";
  @SerializedName(SERIALIZED_NAME_KEY_USAGE)
  private List<Object> keyUsage = null;

  public static final String SERIALIZED_NAME_ORGANIZATION = "Organization";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION)
  private String organization;

  public static final String SERIALIZED_NAME_ORGANIZATIONAL_UNIT = "OrganizationalUnit";
  @SerializedName(SERIALIZED_NAME_ORGANIZATIONAL_UNIT)
  private String organizationalUnit;

  public static final String SERIALIZED_NAME_STATE = "State";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_SURNAME = "Surname";
  @SerializedName(SERIALIZED_NAME_SURNAME)
  private String surname;

  public static final String SERIALIZED_NAME_UNSTRUCTURED_NAME = "UnstructuredName";
  @SerializedName(SERIALIZED_NAME_UNSTRUCTURED_NAME)
  private String unstructuredName;


  public CertificateServiceV104GenerateCSRRequestBody alternativeNames(List<String> alternativeNames) {
    
    this.alternativeNames = alternativeNames;
    return this;
  }

  public CertificateServiceV104GenerateCSRRequestBody addAlternativeNamesItem(String alternativeNamesItem) {
    if (this.alternativeNames == null) {
      this.alternativeNames = new ArrayList<String>();
    }
    this.alternativeNames.add(alternativeNamesItem);
    return this;
  }

   /**
   * The additional host names of the component to secure.
   * @return alternativeNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The additional host names of the component to secure.")

  public List<String> getAlternativeNames() {
    return alternativeNames;
  }


  public void setAlternativeNames(List<String> alternativeNames) {
    this.alternativeNames = alternativeNames;
  }


  public CertificateServiceV104GenerateCSRRequestBody certificateCollection(Object certificateCollection) {
    
    this.certificateCollection = certificateCollection;
    return this;
  }

   /**
   * Get certificateCollection
   * @return certificateCollection
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getCertificateCollection() {
    return certificateCollection;
  }


  public void setCertificateCollection(Object certificateCollection) {
    this.certificateCollection = certificateCollection;
  }


  public CertificateServiceV104GenerateCSRRequestBody challengePassword(String challengePassword) {
    
    this.challengePassword = challengePassword;
    return this;
  }

   /**
   * The challenge password to apply to the certificate for revocation requests.
   * @return challengePassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The challenge password to apply to the certificate for revocation requests.")

  public String getChallengePassword() {
    return challengePassword;
  }


  public void setChallengePassword(String challengePassword) {
    this.challengePassword = challengePassword;
  }


  public CertificateServiceV104GenerateCSRRequestBody city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * The city or locality of the organization making the request.
   * @return city
  **/
  @ApiModelProperty(required = true, value = "The city or locality of the organization making the request.")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public CertificateServiceV104GenerateCSRRequestBody commonName(String commonName) {
    
    this.commonName = commonName;
    return this;
  }

   /**
   * The fully qualified domain name of the component to secure.
   * @return commonName
  **/
  @ApiModelProperty(required = true, value = "The fully qualified domain name of the component to secure.")

  public String getCommonName() {
    return commonName;
  }


  public void setCommonName(String commonName) {
    this.commonName = commonName;
  }


  public CertificateServiceV104GenerateCSRRequestBody contactPerson(String contactPerson) {
    
    this.contactPerson = contactPerson;
    return this;
  }

   /**
   * The name of the user making the request.
   * @return contactPerson
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the user making the request.")

  public String getContactPerson() {
    return contactPerson;
  }


  public void setContactPerson(String contactPerson) {
    this.contactPerson = contactPerson;
  }


  public CertificateServiceV104GenerateCSRRequestBody country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * The two-letter country code of the organization making the request.
   * @return country
  **/
  @ApiModelProperty(required = true, value = "The two-letter country code of the organization making the request.")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public CertificateServiceV104GenerateCSRRequestBody email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * The email address of the contact within the organization making the request.
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The email address of the contact within the organization making the request.")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public CertificateServiceV104GenerateCSRRequestBody givenName(String givenName) {
    
    this.givenName = givenName;
    return this;
  }

   /**
   * The given name of the user making the request.
   * @return givenName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The given name of the user making the request.")

  public String getGivenName() {
    return givenName;
  }


  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }


  public CertificateServiceV104GenerateCSRRequestBody initials(String initials) {
    
    this.initials = initials;
    return this;
  }

   /**
   * The initials of the user making the request.
   * @return initials
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The initials of the user making the request.")

  public String getInitials() {
    return initials;
  }


  public void setInitials(String initials) {
    this.initials = initials;
  }


  public CertificateServiceV104GenerateCSRRequestBody keyBitLength(Long keyBitLength) {
    
    this.keyBitLength = keyBitLength;
    return this;
  }

   /**
   * The length of the key, in bits, if needed based on the KeyPairAlgorithm parameter value.
   * @return keyBitLength
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The length of the key, in bits, if needed based on the KeyPairAlgorithm parameter value.")

  public Long getKeyBitLength() {
    return keyBitLength;
  }


  public void setKeyBitLength(Long keyBitLength) {
    this.keyBitLength = keyBitLength;
  }


  public CertificateServiceV104GenerateCSRRequestBody keyCurveId(String keyCurveId) {
    
    this.keyCurveId = keyCurveId;
    return this;
  }

   /**
   * The curve ID to use with the key, if needed based on the KeyPairAlgorithm parameter value.
   * @return keyCurveId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The curve ID to use with the key, if needed based on the KeyPairAlgorithm parameter value.")

  public String getKeyCurveId() {
    return keyCurveId;
  }


  public void setKeyCurveId(String keyCurveId) {
    this.keyCurveId = keyCurveId;
  }


  public CertificateServiceV104GenerateCSRRequestBody keyPairAlgorithm(String keyPairAlgorithm) {
    
    this.keyPairAlgorithm = keyPairAlgorithm;
    return this;
  }

   /**
   * The type of key-pair for use with signing algorithms.
   * @return keyPairAlgorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of key-pair for use with signing algorithms.")

  public String getKeyPairAlgorithm() {
    return keyPairAlgorithm;
  }


  public void setKeyPairAlgorithm(String keyPairAlgorithm) {
    this.keyPairAlgorithm = keyPairAlgorithm;
  }


  public CertificateServiceV104GenerateCSRRequestBody keyUsage(List<Object> keyUsage) {
    
    this.keyUsage = keyUsage;
    return this;
  }

  public CertificateServiceV104GenerateCSRRequestBody addKeyUsageItem(Object keyUsageItem) {
    if (this.keyUsage == null) {
      this.keyUsage = new ArrayList<Object>();
    }
    this.keyUsage.add(keyUsageItem);
    return this;
  }

   /**
   * The usage of the key contained in the certificate.
   * @return keyUsage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The usage of the key contained in the certificate.")

  public List<Object> getKeyUsage() {
    return keyUsage;
  }


  public void setKeyUsage(List<Object> keyUsage) {
    this.keyUsage = keyUsage;
  }


  public CertificateServiceV104GenerateCSRRequestBody organization(String organization) {
    
    this.organization = organization;
    return this;
  }

   /**
   * The name of the organization making the request.
   * @return organization
  **/
  @ApiModelProperty(required = true, value = "The name of the organization making the request.")

  public String getOrganization() {
    return organization;
  }


  public void setOrganization(String organization) {
    this.organization = organization;
  }


  public CertificateServiceV104GenerateCSRRequestBody organizationalUnit(String organizationalUnit) {
    
    this.organizationalUnit = organizationalUnit;
    return this;
  }

   /**
   * The name of the unit or division of the organization making the request.
   * @return organizationalUnit
  **/
  @ApiModelProperty(required = true, value = "The name of the unit or division of the organization making the request.")

  public String getOrganizationalUnit() {
    return organizationalUnit;
  }


  public void setOrganizationalUnit(String organizationalUnit) {
    this.organizationalUnit = organizationalUnit;
  }


  public CertificateServiceV104GenerateCSRRequestBody state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * The state, province, or region of the organization making the request.
   * @return state
  **/
  @ApiModelProperty(required = true, value = "The state, province, or region of the organization making the request.")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  public CertificateServiceV104GenerateCSRRequestBody surname(String surname) {
    
    this.surname = surname;
    return this;
  }

   /**
   * The surname of the user making the request.
   * @return surname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The surname of the user making the request.")

  public String getSurname() {
    return surname;
  }


  public void setSurname(String surname) {
    this.surname = surname;
  }


  public CertificateServiceV104GenerateCSRRequestBody unstructuredName(String unstructuredName) {
    
    this.unstructuredName = unstructuredName;
    return this;
  }

   /**
   * The unstructured name of the subject.
   * @return unstructuredName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unstructured name of the subject.")

  public String getUnstructuredName() {
    return unstructuredName;
  }


  public void setUnstructuredName(String unstructuredName) {
    this.unstructuredName = unstructuredName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateServiceV104GenerateCSRRequestBody certificateServiceV104GenerateCSRRequestBody = (CertificateServiceV104GenerateCSRRequestBody) o;
    return Objects.equals(this.alternativeNames, certificateServiceV104GenerateCSRRequestBody.alternativeNames) &&
        Objects.equals(this.certificateCollection, certificateServiceV104GenerateCSRRequestBody.certificateCollection) &&
        Objects.equals(this.challengePassword, certificateServiceV104GenerateCSRRequestBody.challengePassword) &&
        Objects.equals(this.city, certificateServiceV104GenerateCSRRequestBody.city) &&
        Objects.equals(this.commonName, certificateServiceV104GenerateCSRRequestBody.commonName) &&
        Objects.equals(this.contactPerson, certificateServiceV104GenerateCSRRequestBody.contactPerson) &&
        Objects.equals(this.country, certificateServiceV104GenerateCSRRequestBody.country) &&
        Objects.equals(this.email, certificateServiceV104GenerateCSRRequestBody.email) &&
        Objects.equals(this.givenName, certificateServiceV104GenerateCSRRequestBody.givenName) &&
        Objects.equals(this.initials, certificateServiceV104GenerateCSRRequestBody.initials) &&
        Objects.equals(this.keyBitLength, certificateServiceV104GenerateCSRRequestBody.keyBitLength) &&
        Objects.equals(this.keyCurveId, certificateServiceV104GenerateCSRRequestBody.keyCurveId) &&
        Objects.equals(this.keyPairAlgorithm, certificateServiceV104GenerateCSRRequestBody.keyPairAlgorithm) &&
        Objects.equals(this.keyUsage, certificateServiceV104GenerateCSRRequestBody.keyUsage) &&
        Objects.equals(this.organization, certificateServiceV104GenerateCSRRequestBody.organization) &&
        Objects.equals(this.organizationalUnit, certificateServiceV104GenerateCSRRequestBody.organizationalUnit) &&
        Objects.equals(this.state, certificateServiceV104GenerateCSRRequestBody.state) &&
        Objects.equals(this.surname, certificateServiceV104GenerateCSRRequestBody.surname) &&
        Objects.equals(this.unstructuredName, certificateServiceV104GenerateCSRRequestBody.unstructuredName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alternativeNames, certificateCollection, challengePassword, city, commonName, contactPerson, country, email, givenName, initials, keyBitLength, keyCurveId, keyPairAlgorithm, keyUsage, organization, organizationalUnit, state, surname, unstructuredName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateServiceV104GenerateCSRRequestBody {\n");
    sb.append("    alternativeNames: ").append(toIndentedString(alternativeNames)).append("\n");
    sb.append("    certificateCollection: ").append(toIndentedString(certificateCollection)).append("\n");
    sb.append("    challengePassword: ").append(toIndentedString(challengePassword)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    commonName: ").append(toIndentedString(commonName)).append("\n");
    sb.append("    contactPerson: ").append(toIndentedString(contactPerson)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    initials: ").append(toIndentedString(initials)).append("\n");
    sb.append("    keyBitLength: ").append(toIndentedString(keyBitLength)).append("\n");
    sb.append("    keyCurveId: ").append(toIndentedString(keyCurveId)).append("\n");
    sb.append("    keyPairAlgorithm: ").append(toIndentedString(keyPairAlgorithm)).append("\n");
    sb.append("    keyUsage: ").append(toIndentedString(keyUsage)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    organizationalUnit: ").append(toIndentedString(organizationalUnit)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    unstructuredName: ").append(toIndentedString(unstructuredName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

