/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The collection of Chassis resource instances.
 */
@ApiModel(description = "The collection of Chassis resource instances.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class ChassisCollectionChassisCollection {
  public static final String SERIALIZED_NAME_AT_ODATA_CONTEXT = "@odata.context";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_CONTEXT)
  private Object atOdataContext = null;

  public static final String SERIALIZED_NAME_AT_ODATA_ETAG = "@odata.etag";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_ETAG)
  private Object atOdataEtag = null;

  public static final String SERIALIZED_NAME_AT_ODATA_ID = "@odata.id";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_ID)
  private Object atOdataId = null;

  public static final String SERIALIZED_NAME_AT_ODATA_TYPE = "@odata.type";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_TYPE)
  private Object atOdataType = null;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private Object description = null;

  public static final String SERIALIZED_NAME_MEMBERS = "Members";
  @SerializedName(SERIALIZED_NAME_MEMBERS)
  private List<Object> members = new ArrayList<Object>();

  public static final String SERIALIZED_NAME_MEMBERS_AT_ODATA_COUNT = "Members@odata.count";
  @SerializedName(SERIALIZED_NAME_MEMBERS_AT_ODATA_COUNT)
  private Object membersAtOdataCount = null;

  public static final String SERIALIZED_NAME_MEMBERS_AT_ODATA_NEXT_LINK = "Members@odata.nextLink";
  @SerializedName(SERIALIZED_NAME_MEMBERS_AT_ODATA_NEXT_LINK)
  private Object membersAtOdataNextLink = null;

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private Object name = null;

  public static final String SERIALIZED_NAME_OEM = "Oem";
  @SerializedName(SERIALIZED_NAME_OEM)
  private Object oem = null;


  public ChassisCollectionChassisCollection atOdataContext(Object atOdataContext) {
    
    this.atOdataContext = atOdataContext;
    return this;
  }

   /**
   * Get atOdataContext
   * @return atOdataContext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAtOdataContext() {
    return atOdataContext;
  }


  public void setAtOdataContext(Object atOdataContext) {
    this.atOdataContext = atOdataContext;
  }


  public ChassisCollectionChassisCollection atOdataEtag(Object atOdataEtag) {
    
    this.atOdataEtag = atOdataEtag;
    return this;
  }

   /**
   * Get atOdataEtag
   * @return atOdataEtag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAtOdataEtag() {
    return atOdataEtag;
  }


  public void setAtOdataEtag(Object atOdataEtag) {
    this.atOdataEtag = atOdataEtag;
  }


  public ChassisCollectionChassisCollection atOdataId(Object atOdataId) {
    
    this.atOdataId = atOdataId;
    return this;
  }

   /**
   * Get atOdataId
   * @return atOdataId
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getAtOdataId() {
    return atOdataId;
  }


  public void setAtOdataId(Object atOdataId) {
    this.atOdataId = atOdataId;
  }


  public ChassisCollectionChassisCollection atOdataType(Object atOdataType) {
    
    this.atOdataType = atOdataType;
    return this;
  }

   /**
   * Get atOdataType
   * @return atOdataType
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getAtOdataType() {
    return atOdataType;
  }


  public void setAtOdataType(Object atOdataType) {
    this.atOdataType = atOdataType;
  }


  public ChassisCollectionChassisCollection description(Object description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getDescription() {
    return description;
  }


  public void setDescription(Object description) {
    this.description = description;
  }


   /**
   * The members of this collection.
   * @return members
  **/
  @ApiModelProperty(required = true, value = "The members of this collection.")

  public List<Object> getMembers() {
    return members;
  }




  public ChassisCollectionChassisCollection membersAtOdataCount(Object membersAtOdataCount) {
    
    this.membersAtOdataCount = membersAtOdataCount;
    return this;
  }

   /**
   * Get membersAtOdataCount
   * @return membersAtOdataCount
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getMembersAtOdataCount() {
    return membersAtOdataCount;
  }


  public void setMembersAtOdataCount(Object membersAtOdataCount) {
    this.membersAtOdataCount = membersAtOdataCount;
  }


  public ChassisCollectionChassisCollection membersAtOdataNextLink(Object membersAtOdataNextLink) {
    
    this.membersAtOdataNextLink = membersAtOdataNextLink;
    return this;
  }

   /**
   * Get membersAtOdataNextLink
   * @return membersAtOdataNextLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getMembersAtOdataNextLink() {
    return membersAtOdataNextLink;
  }


  public void setMembersAtOdataNextLink(Object membersAtOdataNextLink) {
    this.membersAtOdataNextLink = membersAtOdataNextLink;
  }


  public ChassisCollectionChassisCollection name(Object name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getName() {
    return name;
  }


  public void setName(Object name) {
    this.name = name;
  }


  public ChassisCollectionChassisCollection oem(Object oem) {
    
    this.oem = oem;
    return this;
  }

   /**
   * Get oem
   * @return oem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getOem() {
    return oem;
  }


  public void setOem(Object oem) {
    this.oem = oem;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChassisCollectionChassisCollection chassisCollectionChassisCollection = (ChassisCollectionChassisCollection) o;
    return Objects.equals(this.atOdataContext, chassisCollectionChassisCollection.atOdataContext) &&
        Objects.equals(this.atOdataEtag, chassisCollectionChassisCollection.atOdataEtag) &&
        Objects.equals(this.atOdataId, chassisCollectionChassisCollection.atOdataId) &&
        Objects.equals(this.atOdataType, chassisCollectionChassisCollection.atOdataType) &&
        Objects.equals(this.description, chassisCollectionChassisCollection.description) &&
        Objects.equals(this.members, chassisCollectionChassisCollection.members) &&
        Objects.equals(this.membersAtOdataCount, chassisCollectionChassisCollection.membersAtOdataCount) &&
        Objects.equals(this.membersAtOdataNextLink, chassisCollectionChassisCollection.membersAtOdataNextLink) &&
        Objects.equals(this.name, chassisCollectionChassisCollection.name) &&
        Objects.equals(this.oem, chassisCollectionChassisCollection.oem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atOdataContext, atOdataEtag, atOdataId, atOdataType, description, members, membersAtOdataCount, membersAtOdataNextLink, name, oem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChassisCollectionChassisCollection {\n");
    sb.append("    atOdataContext: ").append(toIndentedString(atOdataContext)).append("\n");
    sb.append("    atOdataEtag: ").append(toIndentedString(atOdataEtag)).append("\n");
    sb.append("    atOdataId: ").append(toIndentedString(atOdataId)).append("\n");
    sb.append("    atOdataType: ").append(toIndentedString(atOdataType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    membersAtOdataCount: ").append(toIndentedString(membersAtOdataCount)).append("\n");
    sb.append("    membersAtOdataNextLink: ").append(toIndentedString(membersAtOdataNextLink)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    oem: ").append(toIndentedString(oem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

