/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ConnectionMethod_v1_0_0_ConnectionMethodType
 */
@JsonAdapter(ConnectionMethodV100ConnectionMethodType.Adapter.class)
public enum ConnectionMethodV100ConnectionMethodType {
  
  REDFISH("Redfish"),
  
  SNMP("SNMP"),
  
  IPMI15("IPMI15"),
  
  IPMI20("IPMI20"),
  
  NETCONF("NETCONF"),
  
  OEM("OEM");

  private String value;

  ConnectionMethodV100ConnectionMethodType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ConnectionMethodV100ConnectionMethodType fromValue(String value) {
    for (ConnectionMethodV100ConnectionMethodType b : ConnectionMethodV100ConnectionMethodType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ConnectionMethodV100ConnectionMethodType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ConnectionMethodV100ConnectionMethodType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ConnectionMethodV100ConnectionMethodType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ConnectionMethodV100ConnectionMethodType.fromValue(value);
    }
  }
}

