/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ExternalAccountProviderV120RoleMapping;

/**
 * The ExternalAccountProvider schema represents a remote service that provides accounts for this manager to use for authentication.
 */
@ApiModel(description = "The ExternalAccountProvider schema represents a remote service that provides accounts for this manager to use for authentication.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class ExternalAccountProviderV120ExternalAccountProvider {
  public static final String SERIALIZED_NAME_AT_ODATA_CONTEXT = "@odata.context";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_CONTEXT)
  private Object atOdataContext = null;

  public static final String SERIALIZED_NAME_AT_ODATA_ETAG = "@odata.etag";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_ETAG)
  private Object atOdataEtag = null;

  public static final String SERIALIZED_NAME_AT_ODATA_ID = "@odata.id";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_ID)
  private Object atOdataId = null;

  public static final String SERIALIZED_NAME_AT_ODATA_TYPE = "@odata.type";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_TYPE)
  private Object atOdataType = null;

  public static final String SERIALIZED_NAME_ACCOUNT_PROVIDER_TYPE = "AccountProviderType";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_PROVIDER_TYPE)
  private Object accountProviderType = null;

  public static final String SERIALIZED_NAME_ACTIONS = "Actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private Object actions = null;

  public static final String SERIALIZED_NAME_AUTHENTICATION = "Authentication";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION)
  private Object authentication = null;

  public static final String SERIALIZED_NAME_CERTIFICATES = "Certificates";
  @SerializedName(SERIALIZED_NAME_CERTIFICATES)
  private Object certificates = null;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private Object description = null;

  public static final String SERIALIZED_NAME_ID = "Id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Object id = null;

  public static final String SERIALIZED_NAME_LD_A_P_SERVICE = "LDAPService";
  @SerializedName(SERIALIZED_NAME_LD_A_P_SERVICE)
  private Object ldAPService = null;

  public static final String SERIALIZED_NAME_LINKS = "Links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private Object links = null;

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private Object name = null;

  public static final String SERIALIZED_NAME_OEM = "Oem";
  @SerializedName(SERIALIZED_NAME_OEM)
  private Object oem = null;

  public static final String SERIALIZED_NAME_PRIORITY = "Priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Long priority;

  public static final String SERIALIZED_NAME_REMOTE_ROLE_MAPPING = "RemoteRoleMapping";
  @SerializedName(SERIALIZED_NAME_REMOTE_ROLE_MAPPING)
  private List<ExternalAccountProviderV120RoleMapping> remoteRoleMapping = null;

  public static final String SERIALIZED_NAME_SERVICE_ADDRESSES = "ServiceAddresses";
  @SerializedName(SERIALIZED_NAME_SERVICE_ADDRESSES)
  private List<String> serviceAddresses = null;

  public static final String SERIALIZED_NAME_SERVICE_ENABLED = "ServiceEnabled";
  @SerializedName(SERIALIZED_NAME_SERVICE_ENABLED)
  private Boolean serviceEnabled;

  public static final String SERIALIZED_NAME_TA_C_A_C_SPLUS_SERVICE = "TACACSplusService";
  @SerializedName(SERIALIZED_NAME_TA_C_A_C_SPLUS_SERVICE)
  private Object taCACSplusService = null;


  public ExternalAccountProviderV120ExternalAccountProvider atOdataContext(Object atOdataContext) {
    
    this.atOdataContext = atOdataContext;
    return this;
  }

   /**
   * Get atOdataContext
   * @return atOdataContext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAtOdataContext() {
    return atOdataContext;
  }


  public void setAtOdataContext(Object atOdataContext) {
    this.atOdataContext = atOdataContext;
  }


  public ExternalAccountProviderV120ExternalAccountProvider atOdataEtag(Object atOdataEtag) {
    
    this.atOdataEtag = atOdataEtag;
    return this;
  }

   /**
   * Get atOdataEtag
   * @return atOdataEtag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAtOdataEtag() {
    return atOdataEtag;
  }


  public void setAtOdataEtag(Object atOdataEtag) {
    this.atOdataEtag = atOdataEtag;
  }


  public ExternalAccountProviderV120ExternalAccountProvider atOdataId(Object atOdataId) {
    
    this.atOdataId = atOdataId;
    return this;
  }

   /**
   * Get atOdataId
   * @return atOdataId
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getAtOdataId() {
    return atOdataId;
  }


  public void setAtOdataId(Object atOdataId) {
    this.atOdataId = atOdataId;
  }


  public ExternalAccountProviderV120ExternalAccountProvider atOdataType(Object atOdataType) {
    
    this.atOdataType = atOdataType;
    return this;
  }

   /**
   * Get atOdataType
   * @return atOdataType
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getAtOdataType() {
    return atOdataType;
  }


  public void setAtOdataType(Object atOdataType) {
    this.atOdataType = atOdataType;
  }


  public ExternalAccountProviderV120ExternalAccountProvider accountProviderType(Object accountProviderType) {
    
    this.accountProviderType = accountProviderType;
    return this;
  }

   /**
   * Get accountProviderType
   * @return accountProviderType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAccountProviderType() {
    return accountProviderType;
  }


  public void setAccountProviderType(Object accountProviderType) {
    this.accountProviderType = accountProviderType;
  }


  public ExternalAccountProviderV120ExternalAccountProvider actions(Object actions) {
    
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getActions() {
    return actions;
  }


  public void setActions(Object actions) {
    this.actions = actions;
  }


  public ExternalAccountProviderV120ExternalAccountProvider authentication(Object authentication) {
    
    this.authentication = authentication;
    return this;
  }

   /**
   * Get authentication
   * @return authentication
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAuthentication() {
    return authentication;
  }


  public void setAuthentication(Object authentication) {
    this.authentication = authentication;
  }


  public ExternalAccountProviderV120ExternalAccountProvider certificates(Object certificates) {
    
    this.certificates = certificates;
    return this;
  }

   /**
   * Get certificates
   * @return certificates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getCertificates() {
    return certificates;
  }


  public void setCertificates(Object certificates) {
    this.certificates = certificates;
  }


  public ExternalAccountProviderV120ExternalAccountProvider description(Object description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getDescription() {
    return description;
  }


  public void setDescription(Object description) {
    this.description = description;
  }


  public ExternalAccountProviderV120ExternalAccountProvider id(Object id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getId() {
    return id;
  }


  public void setId(Object id) {
    this.id = id;
  }


  public ExternalAccountProviderV120ExternalAccountProvider ldAPService(Object ldAPService) {
    
    this.ldAPService = ldAPService;
    return this;
  }

   /**
   * Get ldAPService
   * @return ldAPService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getLdAPService() {
    return ldAPService;
  }


  public void setLdAPService(Object ldAPService) {
    this.ldAPService = ldAPService;
  }


  public ExternalAccountProviderV120ExternalAccountProvider links(Object links) {
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getLinks() {
    return links;
  }


  public void setLinks(Object links) {
    this.links = links;
  }


  public ExternalAccountProviderV120ExternalAccountProvider name(Object name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getName() {
    return name;
  }


  public void setName(Object name) {
    this.name = name;
  }


  public ExternalAccountProviderV120ExternalAccountProvider oem(Object oem) {
    
    this.oem = oem;
    return this;
  }

   /**
   * Get oem
   * @return oem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getOem() {
    return oem;
  }


  public void setOem(Object oem) {
    this.oem = oem;
  }


  public ExternalAccountProviderV120ExternalAccountProvider priority(Long priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * The authentication priority for the external account provider.
   * minimum: 0
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The authentication priority for the external account provider.")

  public Long getPriority() {
    return priority;
  }


  public void setPriority(Long priority) {
    this.priority = priority;
  }


  public ExternalAccountProviderV120ExternalAccountProvider remoteRoleMapping(List<ExternalAccountProviderV120RoleMapping> remoteRoleMapping) {
    
    this.remoteRoleMapping = remoteRoleMapping;
    return this;
  }

  public ExternalAccountProviderV120ExternalAccountProvider addRemoteRoleMappingItem(ExternalAccountProviderV120RoleMapping remoteRoleMappingItem) {
    if (this.remoteRoleMapping == null) {
      this.remoteRoleMapping = new ArrayList<ExternalAccountProviderV120RoleMapping>();
    }
    this.remoteRoleMapping.add(remoteRoleMappingItem);
    return this;
  }

   /**
   * The mapping rules to convert the external account providers account information to the local Redfish role.
   * @return remoteRoleMapping
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The mapping rules to convert the external account providers account information to the local Redfish role.")

  public List<ExternalAccountProviderV120RoleMapping> getRemoteRoleMapping() {
    return remoteRoleMapping;
  }


  public void setRemoteRoleMapping(List<ExternalAccountProviderV120RoleMapping> remoteRoleMapping) {
    this.remoteRoleMapping = remoteRoleMapping;
  }


  public ExternalAccountProviderV120ExternalAccountProvider serviceAddresses(List<String> serviceAddresses) {
    
    this.serviceAddresses = serviceAddresses;
    return this;
  }

  public ExternalAccountProviderV120ExternalAccountProvider addServiceAddressesItem(String serviceAddressesItem) {
    if (this.serviceAddresses == null) {
      this.serviceAddresses = new ArrayList<String>();
    }
    this.serviceAddresses.add(serviceAddressesItem);
    return this;
  }

   /**
   * The addresses of the user account providers to which this external account provider links.  The format of this field depends on the type of external account provider.
   * @return serviceAddresses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The addresses of the user account providers to which this external account provider links.  The format of this field depends on the type of external account provider.")

  public List<String> getServiceAddresses() {
    return serviceAddresses;
  }


  public void setServiceAddresses(List<String> serviceAddresses) {
    this.serviceAddresses = serviceAddresses;
  }


  public ExternalAccountProviderV120ExternalAccountProvider serviceEnabled(Boolean serviceEnabled) {
    
    this.serviceEnabled = serviceEnabled;
    return this;
  }

   /**
   * An indication of whether this service is enabled.
   * @return serviceEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An indication of whether this service is enabled.")

  public Boolean getServiceEnabled() {
    return serviceEnabled;
  }


  public void setServiceEnabled(Boolean serviceEnabled) {
    this.serviceEnabled = serviceEnabled;
  }


  public ExternalAccountProviderV120ExternalAccountProvider taCACSplusService(Object taCACSplusService) {
    
    this.taCACSplusService = taCACSplusService;
    return this;
  }

   /**
   * Get taCACSplusService
   * @return taCACSplusService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getTaCACSplusService() {
    return taCACSplusService;
  }


  public void setTaCACSplusService(Object taCACSplusService) {
    this.taCACSplusService = taCACSplusService;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalAccountProviderV120ExternalAccountProvider externalAccountProviderV120ExternalAccountProvider = (ExternalAccountProviderV120ExternalAccountProvider) o;
    return Objects.equals(this.atOdataContext, externalAccountProviderV120ExternalAccountProvider.atOdataContext) &&
        Objects.equals(this.atOdataEtag, externalAccountProviderV120ExternalAccountProvider.atOdataEtag) &&
        Objects.equals(this.atOdataId, externalAccountProviderV120ExternalAccountProvider.atOdataId) &&
        Objects.equals(this.atOdataType, externalAccountProviderV120ExternalAccountProvider.atOdataType) &&
        Objects.equals(this.accountProviderType, externalAccountProviderV120ExternalAccountProvider.accountProviderType) &&
        Objects.equals(this.actions, externalAccountProviderV120ExternalAccountProvider.actions) &&
        Objects.equals(this.authentication, externalAccountProviderV120ExternalAccountProvider.authentication) &&
        Objects.equals(this.certificates, externalAccountProviderV120ExternalAccountProvider.certificates) &&
        Objects.equals(this.description, externalAccountProviderV120ExternalAccountProvider.description) &&
        Objects.equals(this.id, externalAccountProviderV120ExternalAccountProvider.id) &&
        Objects.equals(this.ldAPService, externalAccountProviderV120ExternalAccountProvider.ldAPService) &&
        Objects.equals(this.links, externalAccountProviderV120ExternalAccountProvider.links) &&
        Objects.equals(this.name, externalAccountProviderV120ExternalAccountProvider.name) &&
        Objects.equals(this.oem, externalAccountProviderV120ExternalAccountProvider.oem) &&
        Objects.equals(this.priority, externalAccountProviderV120ExternalAccountProvider.priority) &&
        Objects.equals(this.remoteRoleMapping, externalAccountProviderV120ExternalAccountProvider.remoteRoleMapping) &&
        Objects.equals(this.serviceAddresses, externalAccountProviderV120ExternalAccountProvider.serviceAddresses) &&
        Objects.equals(this.serviceEnabled, externalAccountProviderV120ExternalAccountProvider.serviceEnabled) &&
        Objects.equals(this.taCACSplusService, externalAccountProviderV120ExternalAccountProvider.taCACSplusService);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atOdataContext, atOdataEtag, atOdataId, atOdataType, accountProviderType, actions, authentication, certificates, description, id, ldAPService, links, name, oem, priority, remoteRoleMapping, serviceAddresses, serviceEnabled, taCACSplusService);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalAccountProviderV120ExternalAccountProvider {\n");
    sb.append("    atOdataContext: ").append(toIndentedString(atOdataContext)).append("\n");
    sb.append("    atOdataEtag: ").append(toIndentedString(atOdataEtag)).append("\n");
    sb.append("    atOdataId: ").append(toIndentedString(atOdataId)).append("\n");
    sb.append("    atOdataType: ").append(toIndentedString(atOdataType)).append("\n");
    sb.append("    accountProviderType: ").append(toIndentedString(accountProviderType)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("    certificates: ").append(toIndentedString(certificates)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ldAPService: ").append(toIndentedString(ldAPService)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    oem: ").append(toIndentedString(oem)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    remoteRoleMapping: ").append(toIndentedString(remoteRoleMapping)).append("\n");
    sb.append("    serviceAddresses: ").append(toIndentedString(serviceAddresses)).append("\n");
    sb.append("    serviceEnabled: ").append(toIndentedString(serviceEnabled)).append("\n");
    sb.append("    taCACSplusService: ").append(toIndentedString(taCACSplusService)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

