/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The SNMP settings for an account.
 */
@ApiModel(description = "The SNMP settings for an account.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class ManagerAccountV180SNMPUserInfo {
  public static final String SERIALIZED_NAME_AUTHENTICATION_KEY = "AuthenticationKey";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_KEY)
  private String authenticationKey;

  public static final String SERIALIZED_NAME_AUTHENTICATION_KEY_SET = "AuthenticationKeySet";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_KEY_SET)
  private Boolean authenticationKeySet;

  public static final String SERIALIZED_NAME_AUTHENTICATION_PROTOCOL = "AuthenticationProtocol";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_PROTOCOL)
  private Object authenticationProtocol = null;

  public static final String SERIALIZED_NAME_ENCRYPTION_KEY = "EncryptionKey";
  @SerializedName(SERIALIZED_NAME_ENCRYPTION_KEY)
  private String encryptionKey;

  public static final String SERIALIZED_NAME_ENCRYPTION_KEY_SET = "EncryptionKeySet";
  @SerializedName(SERIALIZED_NAME_ENCRYPTION_KEY_SET)
  private Boolean encryptionKeySet;

  public static final String SERIALIZED_NAME_ENCRYPTION_PROTOCOL = "EncryptionProtocol";
  @SerializedName(SERIALIZED_NAME_ENCRYPTION_PROTOCOL)
  private Object encryptionProtocol = null;


  public ManagerAccountV180SNMPUserInfo authenticationKey(String authenticationKey) {
    
    this.authenticationKey = authenticationKey;
    return this;
  }

   /**
   * The secret authentication key for SNMPv3.
   * @return authenticationKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The secret authentication key for SNMPv3.")

  public String getAuthenticationKey() {
    return authenticationKey;
  }


  public void setAuthenticationKey(String authenticationKey) {
    this.authenticationKey = authenticationKey;
  }


   /**
   * Indicates if the AuthenticationKey property is set.
   * @return authenticationKeySet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates if the AuthenticationKey property is set.")

  public Boolean getAuthenticationKeySet() {
    return authenticationKeySet;
  }




  public ManagerAccountV180SNMPUserInfo authenticationProtocol(Object authenticationProtocol) {
    
    this.authenticationProtocol = authenticationProtocol;
    return this;
  }

   /**
   * Get authenticationProtocol
   * @return authenticationProtocol
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAuthenticationProtocol() {
    return authenticationProtocol;
  }


  public void setAuthenticationProtocol(Object authenticationProtocol) {
    this.authenticationProtocol = authenticationProtocol;
  }


  public ManagerAccountV180SNMPUserInfo encryptionKey(String encryptionKey) {
    
    this.encryptionKey = encryptionKey;
    return this;
  }

   /**
   * The secret encryption key used in SNMPv3.
   * @return encryptionKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The secret encryption key used in SNMPv3.")

  public String getEncryptionKey() {
    return encryptionKey;
  }


  public void setEncryptionKey(String encryptionKey) {
    this.encryptionKey = encryptionKey;
  }


   /**
   * Indicates if the EncryptionKey property is set.
   * @return encryptionKeySet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates if the EncryptionKey property is set.")

  public Boolean getEncryptionKeySet() {
    return encryptionKeySet;
  }




  public ManagerAccountV180SNMPUserInfo encryptionProtocol(Object encryptionProtocol) {
    
    this.encryptionProtocol = encryptionProtocol;
    return this;
  }

   /**
   * Get encryptionProtocol
   * @return encryptionProtocol
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getEncryptionProtocol() {
    return encryptionProtocol;
  }


  public void setEncryptionProtocol(Object encryptionProtocol) {
    this.encryptionProtocol = encryptionProtocol;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManagerAccountV180SNMPUserInfo managerAccountV180SNMPUserInfo = (ManagerAccountV180SNMPUserInfo) o;
    return Objects.equals(this.authenticationKey, managerAccountV180SNMPUserInfo.authenticationKey) &&
        Objects.equals(this.authenticationKeySet, managerAccountV180SNMPUserInfo.authenticationKeySet) &&
        Objects.equals(this.authenticationProtocol, managerAccountV180SNMPUserInfo.authenticationProtocol) &&
        Objects.equals(this.encryptionKey, managerAccountV180SNMPUserInfo.encryptionKey) &&
        Objects.equals(this.encryptionKeySet, managerAccountV180SNMPUserInfo.encryptionKeySet) &&
        Objects.equals(this.encryptionProtocol, managerAccountV180SNMPUserInfo.encryptionProtocol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticationKey, authenticationKeySet, authenticationProtocol, encryptionKey, encryptionKeySet, encryptionProtocol);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManagerAccountV180SNMPUserInfo {\n");
    sb.append("    authenticationKey: ").append(toIndentedString(authenticationKey)).append("\n");
    sb.append("    authenticationKeySet: ").append(toIndentedString(authenticationKeySet)).append("\n");
    sb.append("    authenticationProtocol: ").append(toIndentedString(authenticationProtocol)).append("\n");
    sb.append("    encryptionKey: ").append(toIndentedString(encryptionKey)).append("\n");
    sb.append("    encryptionKeySet: ").append(toIndentedString(encryptionKeySet)).append("\n");
    sb.append("    encryptionProtocol: ").append(toIndentedString(encryptionProtocol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

