/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ManagerAccount_v1_8_0_SNMPAuthenticationProtocols
 */
@JsonAdapter(ManagerAccountV180SNMPAuthenticationProtocols.Adapter.class)
public enum ManagerAccountV180SNMPAuthenticationProtocols {
  
  NONE("None"),
  
  HMAC_MD5("HMAC_MD5"),
  
  HMAC_SHA96("HMAC_SHA96"),
  
  HMAC128_SHA224("HMAC128_SHA224"),
  
  HMAC192_SHA256("HMAC192_SHA256"),
  
  HMAC256_SHA384("HMAC256_SHA384"),
  
  HMAC384_SHA512("HMAC384_SHA512");

  private String value;

  ManagerAccountV180SNMPAuthenticationProtocols(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ManagerAccountV180SNMPAuthenticationProtocols fromValue(String value) {
    for (ManagerAccountV180SNMPAuthenticationProtocols b : ManagerAccountV180SNMPAuthenticationProtocols.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ManagerAccountV180SNMPAuthenticationProtocols> {
    @Override
    public void write(final JsonWriter jsonWriter, final ManagerAccountV180SNMPAuthenticationProtocols enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ManagerAccountV180SNMPAuthenticationProtocols read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ManagerAccountV180SNMPAuthenticationProtocols.fromValue(value);
    }
  }
}

