/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ManagerAccount_AccountTypes
 */
@JsonAdapter(ManagerAccountAccountTypes.Adapter.class)
public enum ManagerAccountAccountTypes {
  
  REDFISH("Redfish"),
  
  SNMP("SNMP"),
  
  OEM("OEM"),
  
  HOSTCONSOLE("HostConsole"),
  
  MANAGERCONSOLE("ManagerConsole"),
  
  IPMI("IPMI"),
  
  KVMIP("KVMIP"),
  
  VIRTUALMEDIA("VirtualMedia"),
  
  WEBUI("WebUI");

  private String value;

  ManagerAccountAccountTypes(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ManagerAccountAccountTypes fromValue(String value) {
    for (ManagerAccountAccountTypes b : ManagerAccountAccountTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ManagerAccountAccountTypes> {
    @Override
    public void write(final JsonWriter jsonWriter, final ManagerAccountAccountTypes enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ManagerAccountAccountTypes read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ManagerAccountAccountTypes.fromValue(value);
    }
  }
}

