/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The reference areas for the location of the part within an enclosure.
 */
@JsonAdapter(ResourceV187Reference.Adapter.class)
public enum ResourceV187Reference {
  
  TOP("Top"),
  
  BOTTOM("Bottom"),
  
  FRONT("Front"),
  
  REAR("Rear"),
  
  LEFT("Left"),
  
  RIGHT("Right"),
  
  MIDDLE("Middle");

  private String value;

  ResourceV187Reference(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ResourceV187Reference fromValue(String value) {
    for (ResourceV187Reference b : ResourceV187Reference.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ResourceV187Reference> {
    @Override
    public void write(final JsonWriter jsonWriter, final ResourceV187Reference enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ResourceV187Reference read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ResourceV187Reference.fromValue(value);
    }
  }
}

