/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The location of a resource.
 */
@ApiModel(description = "The location of a resource.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class ResourceV1113Location {
  public static final String SERIALIZED_NAME_INFO = "Info";
  @SerializedName(SERIALIZED_NAME_INFO)
  private String info;

  public static final String SERIALIZED_NAME_INFO_FORMAT = "InfoFormat";
  @SerializedName(SERIALIZED_NAME_INFO_FORMAT)
  private String infoFormat;

  public static final String SERIALIZED_NAME_OEM = "Oem";
  @SerializedName(SERIALIZED_NAME_OEM)
  private Object oem = null;


   /**
   * The location of the resource.
   * @return info
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The location of the resource.")

  public String getInfo() {
    return info;
  }




   /**
   * The format of the Info property.
   * @return infoFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The format of the Info property.")

  public String getInfoFormat() {
    return infoFormat;
  }




  public ResourceV1113Location oem(Object oem) {
    
    this.oem = oem;
    return this;
  }

   /**
   * Get oem
   * @return oem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getOem() {
    return oem;
  }


  public void setOem(Object oem) {
    this.oem = oem;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceV1113Location resourceV1113Location = (ResourceV1113Location) o;
    return Objects.equals(this.info, resourceV1113Location.info) &&
        Objects.equals(this.infoFormat, resourceV1113Location.infoFormat) &&
        Objects.equals(this.oem, resourceV1113Location.oem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(info, infoFormat, oem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceV1113Location {\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    infoFormat: ").append(toIndentedString(infoFormat)).append("\n");
    sb.append("    oem: ").append(toIndentedString(oem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

