/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The orientations for the ordering of the part location ordinal value.
 */
@JsonAdapter(ResourceV1111Orientation.Adapter.class)
public enum ResourceV1111Orientation {
  
  FRONTTOBACK("FrontToBack"),
  
  BACKTOFRONT("BackToFront"),
  
  TOPTOBOTTOM("TopToBottom"),
  
  BOTTOMTOTOP("BottomToTop"),
  
  LEFTTORIGHT("LeftToRight"),
  
  RIGHTTOLEFT("RightToLeft");

  private String value;

  ResourceV1111Orientation(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ResourceV1111Orientation fromValue(String value) {
    for (ResourceV1111Orientation b : ResourceV1111Orientation.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ResourceV1111Orientation> {
    @Override
    public void write(final JsonWriter jsonWriter, final ResourceV1111Orientation enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ResourceV1111Orientation read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ResourceV1111Orientation.fromValue(value);
    }
  }
}

