/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ResourceCondition;

/**
 * The status and health of a resource and its children.
 */
@ApiModel(description = "The status and health of a resource and its children.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class ResourceStatus {
  public static final String SERIALIZED_NAME_CONDITIONS = "Conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<ResourceCondition> conditions = null;

  public static final String SERIALIZED_NAME_HEALTH = "Health";
  @SerializedName(SERIALIZED_NAME_HEALTH)
  private Object health = null;

  public static final String SERIALIZED_NAME_HEALTH_ROLLUP = "HealthRollup";
  @SerializedName(SERIALIZED_NAME_HEALTH_ROLLUP)
  private Object healthRollup = null;

  public static final String SERIALIZED_NAME_OEM = "Oem";
  @SerializedName(SERIALIZED_NAME_OEM)
  private Object oem = null;

  public static final String SERIALIZED_NAME_STATE = "State";
  @SerializedName(SERIALIZED_NAME_STATE)
  private Object state = null;


  public ResourceStatus conditions(List<ResourceCondition> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public ResourceStatus addConditionsItem(ResourceCondition conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<ResourceCondition>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Conditions in this resource that require attention.
   * @return conditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Conditions in this resource that require attention.")

  public List<ResourceCondition> getConditions() {
    return conditions;
  }


  public void setConditions(List<ResourceCondition> conditions) {
    this.conditions = conditions;
  }


  public ResourceStatus health(Object health) {
    
    this.health = health;
    return this;
  }

   /**
   * Get health
   * @return health
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getHealth() {
    return health;
  }


  public void setHealth(Object health) {
    this.health = health;
  }


  public ResourceStatus healthRollup(Object healthRollup) {
    
    this.healthRollup = healthRollup;
    return this;
  }

   /**
   * Get healthRollup
   * @return healthRollup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getHealthRollup() {
    return healthRollup;
  }


  public void setHealthRollup(Object healthRollup) {
    this.healthRollup = healthRollup;
  }


  public ResourceStatus oem(Object oem) {
    
    this.oem = oem;
    return this;
  }

   /**
   * Get oem
   * @return oem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getOem() {
    return oem;
  }


  public void setOem(Object oem) {
    this.oem = oem;
  }


  public ResourceStatus state(Object state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getState() {
    return state;
  }


  public void setState(Object state) {
    this.state = state;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceStatus resourceStatus = (ResourceStatus) o;
    return Objects.equals(this.conditions, resourceStatus.conditions) &&
        Objects.equals(this.health, resourceStatus.health) &&
        Objects.equals(this.healthRollup, resourceStatus.healthRollup) &&
        Objects.equals(this.oem, resourceStatus.oem) &&
        Objects.equals(this.state, resourceStatus.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditions, health, healthRollup, oem, state);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceStatus {\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    health: ").append(toIndentedString(health)).append("\n");
    sb.append("    healthRollup: ").append(toIndentedString(healthRollup)).append("\n");
    sb.append("    oem: ").append(toIndentedString(oem)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

