/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * A condition that requires attention.
 */
@ApiModel(description = "A condition that requires attention.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class ResourceCondition {
  public static final String SERIALIZED_NAME_LOG_ENTRY = "LogEntry";
  @SerializedName(SERIALIZED_NAME_LOG_ENTRY)
  private Object logEntry = null;

  public static final String SERIALIZED_NAME_MESSAGE = "Message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_MESSAGE_ARGS = "MessageArgs";
  @SerializedName(SERIALIZED_NAME_MESSAGE_ARGS)
  private List<String> messageArgs = null;

  public static final String SERIALIZED_NAME_MESSAGE_ID = "MessageId";
  @SerializedName(SERIALIZED_NAME_MESSAGE_ID)
  private String messageId;

  public static final String SERIALIZED_NAME_ORIGIN_OF_CONDITION = "OriginOfCondition";
  @SerializedName(SERIALIZED_NAME_ORIGIN_OF_CONDITION)
  private Object originOfCondition = null;

  public static final String SERIALIZED_NAME_SEVERITY = "Severity";
  @SerializedName(SERIALIZED_NAME_SEVERITY)
  private Object severity = null;

  public static final String SERIALIZED_NAME_TIMESTAMP = "Timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private OffsetDateTime timestamp;


  public ResourceCondition logEntry(Object logEntry) {
    
    this.logEntry = logEntry;
    return this;
  }

   /**
   * Get logEntry
   * @return logEntry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getLogEntry() {
    return logEntry;
  }


  public void setLogEntry(Object logEntry) {
    this.logEntry = logEntry;
  }


   /**
   * The human-readable message for this condition.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The human-readable message for this condition.")

  public String getMessage() {
    return message;
  }




   /**
   * An array of message arguments that are substituted for the arguments in the message when looked up in the message registry.
   * @return messageArgs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of message arguments that are substituted for the arguments in the message when looked up in the message registry.")

  public List<String> getMessageArgs() {
    return messageArgs;
  }




   /**
   * The identifier for the message.
   * @return messageId
  **/
  @ApiModelProperty(required = true, value = "The identifier for the message.")

  public String getMessageId() {
    return messageId;
  }




  public ResourceCondition originOfCondition(Object originOfCondition) {
    
    this.originOfCondition = originOfCondition;
    return this;
  }

   /**
   * Get originOfCondition
   * @return originOfCondition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getOriginOfCondition() {
    return originOfCondition;
  }


  public void setOriginOfCondition(Object originOfCondition) {
    this.originOfCondition = originOfCondition;
  }


  public ResourceCondition severity(Object severity) {
    
    this.severity = severity;
    return this;
  }

   /**
   * Get severity
   * @return severity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getSeverity() {
    return severity;
  }


  public void setSeverity(Object severity) {
    this.severity = severity;
  }


   /**
   * The time the condition occurred.
   * @return timestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time the condition occurred.")

  public OffsetDateTime getTimestamp() {
    return timestamp;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceCondition resourceCondition = (ResourceCondition) o;
    return Objects.equals(this.logEntry, resourceCondition.logEntry) &&
        Objects.equals(this.message, resourceCondition.message) &&
        Objects.equals(this.messageArgs, resourceCondition.messageArgs) &&
        Objects.equals(this.messageId, resourceCondition.messageId) &&
        Objects.equals(this.originOfCondition, resourceCondition.originOfCondition) &&
        Objects.equals(this.severity, resourceCondition.severity) &&
        Objects.equals(this.timestamp, resourceCondition.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logEntry, message, messageArgs, messageId, originOfCondition, severity, timestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceCondition {\n");
    sb.append("    logEntry: ").append(toIndentedString(logEntry)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    messageArgs: ").append(toIndentedString(messageArgs)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    originOfCondition: ").append(toIndentedString(originOfCondition)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

