/*
 * Redfish
 * This contains the definition of a Redfish service.
 *
 * The version of the OpenAPI document: 2021.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The ServiceRoot schema describes the root of the Redfish Service, located at the &#39;/redfish/v1&#39; URI.  All other Resources accessible through the Redfish interface on this device are linked directly or indirectly from the Service Root.
 */
@ApiModel(description = "The ServiceRoot schema describes the root of the Redfish Service, located at the '/redfish/v1' URI.  All other Resources accessible through the Redfish interface on this device are linked directly or indirectly from the Service Root.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-24T10:33:09.083984300-06:00[America/Denver]")
public class ServiceRootV1100ServiceRoot {
  public static final String SERIALIZED_NAME_AT_ODATA_CONTEXT = "@odata.context";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_CONTEXT)
  private Object atOdataContext = null;

  public static final String SERIALIZED_NAME_AT_ODATA_ETAG = "@odata.etag";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_ETAG)
  private Object atOdataEtag = null;

  public static final String SERIALIZED_NAME_AT_ODATA_ID = "@odata.id";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_ID)
  private Object atOdataId = null;

  public static final String SERIALIZED_NAME_AT_ODATA_TYPE = "@odata.type";
  @SerializedName(SERIALIZED_NAME_AT_ODATA_TYPE)
  private Object atOdataType = null;

  public static final String SERIALIZED_NAME_ACCOUNT_SERVICE = "AccountService";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_SERVICE)
  private Object accountService = null;

  public static final String SERIALIZED_NAME_AGGREGATION_SERVICE = "AggregationService";
  @SerializedName(SERIALIZED_NAME_AGGREGATION_SERVICE)
  private Object aggregationService = null;

  public static final String SERIALIZED_NAME_CERTIFICATE_SERVICE = "CertificateService";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE_SERVICE)
  private Object certificateService = null;

  public static final String SERIALIZED_NAME_CHASSIS = "Chassis";
  @SerializedName(SERIALIZED_NAME_CHASSIS)
  private Object chassis = null;

  public static final String SERIALIZED_NAME_COMPOSITION_SERVICE = "CompositionService";
  @SerializedName(SERIALIZED_NAME_COMPOSITION_SERVICE)
  private Object compositionService = null;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private Object description = null;

  public static final String SERIALIZED_NAME_EVENT_SERVICE = "EventService";
  @SerializedName(SERIALIZED_NAME_EVENT_SERVICE)
  private Object eventService = null;

  public static final String SERIALIZED_NAME_FABRICS = "Fabrics";
  @SerializedName(SERIALIZED_NAME_FABRICS)
  private Object fabrics = null;

  public static final String SERIALIZED_NAME_FACILITIES = "Facilities";
  @SerializedName(SERIALIZED_NAME_FACILITIES)
  private Object facilities = null;

  public static final String SERIALIZED_NAME_ID = "Id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Object id = null;

  public static final String SERIALIZED_NAME_JOB_SERVICE = "JobService";
  @SerializedName(SERIALIZED_NAME_JOB_SERVICE)
  private Object jobService = null;

  public static final String SERIALIZED_NAME_JSON_SCHEMAS = "JsonSchemas";
  @SerializedName(SERIALIZED_NAME_JSON_SCHEMAS)
  private Object jsonSchemas = null;

  public static final String SERIALIZED_NAME_LINKS = "Links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private Object links = null;

  public static final String SERIALIZED_NAME_MANAGERS = "Managers";
  @SerializedName(SERIALIZED_NAME_MANAGERS)
  private Object managers = null;

  public static final String SERIALIZED_NAME_NV_ME_DOMAINS = "NVMeDomains";
  @SerializedName(SERIALIZED_NAME_NV_ME_DOMAINS)
  private Object nvMeDomains = null;

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private Object name = null;

  public static final String SERIALIZED_NAME_OEM = "Oem";
  @SerializedName(SERIALIZED_NAME_OEM)
  private Object oem = null;

  public static final String SERIALIZED_NAME_POWER_EQUIPMENT = "PowerEquipment";
  @SerializedName(SERIALIZED_NAME_POWER_EQUIPMENT)
  private Object powerEquipment = null;

  public static final String SERIALIZED_NAME_PRODUCT = "Product";
  @SerializedName(SERIALIZED_NAME_PRODUCT)
  private String product;

  public static final String SERIALIZED_NAME_PROTOCOL_FEATURES_SUPPORTED = "ProtocolFeaturesSupported";
  @SerializedName(SERIALIZED_NAME_PROTOCOL_FEATURES_SUPPORTED)
  private Object protocolFeaturesSupported = null;

  public static final String SERIALIZED_NAME_REDFISH_VERSION = "RedfishVersion";
  @SerializedName(SERIALIZED_NAME_REDFISH_VERSION)
  private String redfishVersion;

  public static final String SERIALIZED_NAME_REGISTRIES = "Registries";
  @SerializedName(SERIALIZED_NAME_REGISTRIES)
  private Object registries = null;

  public static final String SERIALIZED_NAME_RESOURCE_BLOCKS = "ResourceBlocks";
  @SerializedName(SERIALIZED_NAME_RESOURCE_BLOCKS)
  private Object resourceBlocks = null;

  public static final String SERIALIZED_NAME_SESSION_SERVICE = "SessionService";
  @SerializedName(SERIALIZED_NAME_SESSION_SERVICE)
  private Object sessionService = null;

  public static final String SERIALIZED_NAME_STORAGE = "Storage";
  @SerializedName(SERIALIZED_NAME_STORAGE)
  private Object storage = null;

  public static final String SERIALIZED_NAME_STORAGE_SERVICES = "StorageServices";
  @SerializedName(SERIALIZED_NAME_STORAGE_SERVICES)
  private Object storageServices = null;

  public static final String SERIALIZED_NAME_STORAGE_SYSTEMS = "StorageSystems";
  @SerializedName(SERIALIZED_NAME_STORAGE_SYSTEMS)
  private Object storageSystems = null;

  public static final String SERIALIZED_NAME_SYSTEMS = "Systems";
  @SerializedName(SERIALIZED_NAME_SYSTEMS)
  private Object systems = null;

  public static final String SERIALIZED_NAME_TASKS = "Tasks";
  @SerializedName(SERIALIZED_NAME_TASKS)
  private Object tasks = null;

  public static final String SERIALIZED_NAME_TELEMETRY_SERVICE = "TelemetryService";
  @SerializedName(SERIALIZED_NAME_TELEMETRY_SERVICE)
  private Object telemetryService = null;

  public static final String SERIALIZED_NAME_U_U_I_D = "UUID";
  @SerializedName(SERIALIZED_NAME_U_U_I_D)
  private Object UUID = null;

  public static final String SERIALIZED_NAME_UPDATE_SERVICE = "UpdateService";
  @SerializedName(SERIALIZED_NAME_UPDATE_SERVICE)
  private Object updateService = null;

  public static final String SERIALIZED_NAME_VENDOR = "Vendor";
  @SerializedName(SERIALIZED_NAME_VENDOR)
  private String vendor;


  public ServiceRootV1100ServiceRoot atOdataContext(Object atOdataContext) {
    
    this.atOdataContext = atOdataContext;
    return this;
  }

   /**
   * Get atOdataContext
   * @return atOdataContext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAtOdataContext() {
    return atOdataContext;
  }


  public void setAtOdataContext(Object atOdataContext) {
    this.atOdataContext = atOdataContext;
  }


  public ServiceRootV1100ServiceRoot atOdataEtag(Object atOdataEtag) {
    
    this.atOdataEtag = atOdataEtag;
    return this;
  }

   /**
   * Get atOdataEtag
   * @return atOdataEtag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAtOdataEtag() {
    return atOdataEtag;
  }


  public void setAtOdataEtag(Object atOdataEtag) {
    this.atOdataEtag = atOdataEtag;
  }


  public ServiceRootV1100ServiceRoot atOdataId(Object atOdataId) {
    
    this.atOdataId = atOdataId;
    return this;
  }

   /**
   * Get atOdataId
   * @return atOdataId
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getAtOdataId() {
    return atOdataId;
  }


  public void setAtOdataId(Object atOdataId) {
    this.atOdataId = atOdataId;
  }


  public ServiceRootV1100ServiceRoot atOdataType(Object atOdataType) {
    
    this.atOdataType = atOdataType;
    return this;
  }

   /**
   * Get atOdataType
   * @return atOdataType
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getAtOdataType() {
    return atOdataType;
  }


  public void setAtOdataType(Object atOdataType) {
    this.atOdataType = atOdataType;
  }


  public ServiceRootV1100ServiceRoot accountService(Object accountService) {
    
    this.accountService = accountService;
    return this;
  }

   /**
   * Get accountService
   * @return accountService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAccountService() {
    return accountService;
  }


  public void setAccountService(Object accountService) {
    this.accountService = accountService;
  }


  public ServiceRootV1100ServiceRoot aggregationService(Object aggregationService) {
    
    this.aggregationService = aggregationService;
    return this;
  }

   /**
   * Get aggregationService
   * @return aggregationService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAggregationService() {
    return aggregationService;
  }


  public void setAggregationService(Object aggregationService) {
    this.aggregationService = aggregationService;
  }


  public ServiceRootV1100ServiceRoot certificateService(Object certificateService) {
    
    this.certificateService = certificateService;
    return this;
  }

   /**
   * Get certificateService
   * @return certificateService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getCertificateService() {
    return certificateService;
  }


  public void setCertificateService(Object certificateService) {
    this.certificateService = certificateService;
  }


  public ServiceRootV1100ServiceRoot chassis(Object chassis) {
    
    this.chassis = chassis;
    return this;
  }

   /**
   * Get chassis
   * @return chassis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getChassis() {
    return chassis;
  }


  public void setChassis(Object chassis) {
    this.chassis = chassis;
  }


  public ServiceRootV1100ServiceRoot compositionService(Object compositionService) {
    
    this.compositionService = compositionService;
    return this;
  }

   /**
   * Get compositionService
   * @return compositionService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getCompositionService() {
    return compositionService;
  }


  public void setCompositionService(Object compositionService) {
    this.compositionService = compositionService;
  }


  public ServiceRootV1100ServiceRoot description(Object description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getDescription() {
    return description;
  }


  public void setDescription(Object description) {
    this.description = description;
  }


  public ServiceRootV1100ServiceRoot eventService(Object eventService) {
    
    this.eventService = eventService;
    return this;
  }

   /**
   * Get eventService
   * @return eventService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getEventService() {
    return eventService;
  }


  public void setEventService(Object eventService) {
    this.eventService = eventService;
  }


  public ServiceRootV1100ServiceRoot fabrics(Object fabrics) {
    
    this.fabrics = fabrics;
    return this;
  }

   /**
   * Get fabrics
   * @return fabrics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getFabrics() {
    return fabrics;
  }


  public void setFabrics(Object fabrics) {
    this.fabrics = fabrics;
  }


  public ServiceRootV1100ServiceRoot facilities(Object facilities) {
    
    this.facilities = facilities;
    return this;
  }

   /**
   * Get facilities
   * @return facilities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getFacilities() {
    return facilities;
  }


  public void setFacilities(Object facilities) {
    this.facilities = facilities;
  }


  public ServiceRootV1100ServiceRoot id(Object id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getId() {
    return id;
  }


  public void setId(Object id) {
    this.id = id;
  }


  public ServiceRootV1100ServiceRoot jobService(Object jobService) {
    
    this.jobService = jobService;
    return this;
  }

   /**
   * Get jobService
   * @return jobService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getJobService() {
    return jobService;
  }


  public void setJobService(Object jobService) {
    this.jobService = jobService;
  }


  public ServiceRootV1100ServiceRoot jsonSchemas(Object jsonSchemas) {
    
    this.jsonSchemas = jsonSchemas;
    return this;
  }

   /**
   * Get jsonSchemas
   * @return jsonSchemas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getJsonSchemas() {
    return jsonSchemas;
  }


  public void setJsonSchemas(Object jsonSchemas) {
    this.jsonSchemas = jsonSchemas;
  }


  public ServiceRootV1100ServiceRoot links(Object links) {
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getLinks() {
    return links;
  }


  public void setLinks(Object links) {
    this.links = links;
  }


  public ServiceRootV1100ServiceRoot managers(Object managers) {
    
    this.managers = managers;
    return this;
  }

   /**
   * Get managers
   * @return managers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getManagers() {
    return managers;
  }


  public void setManagers(Object managers) {
    this.managers = managers;
  }


  public ServiceRootV1100ServiceRoot nvMeDomains(Object nvMeDomains) {
    
    this.nvMeDomains = nvMeDomains;
    return this;
  }

   /**
   * Get nvMeDomains
   * @return nvMeDomains
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getNvMeDomains() {
    return nvMeDomains;
  }


  public void setNvMeDomains(Object nvMeDomains) {
    this.nvMeDomains = nvMeDomains;
  }


  public ServiceRootV1100ServiceRoot name(Object name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getName() {
    return name;
  }


  public void setName(Object name) {
    this.name = name;
  }


  public ServiceRootV1100ServiceRoot oem(Object oem) {
    
    this.oem = oem;
    return this;
  }

   /**
   * Get oem
   * @return oem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getOem() {
    return oem;
  }


  public void setOem(Object oem) {
    this.oem = oem;
  }


  public ServiceRootV1100ServiceRoot powerEquipment(Object powerEquipment) {
    
    this.powerEquipment = powerEquipment;
    return this;
  }

   /**
   * Get powerEquipment
   * @return powerEquipment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getPowerEquipment() {
    return powerEquipment;
  }


  public void setPowerEquipment(Object powerEquipment) {
    this.powerEquipment = powerEquipment;
  }


   /**
   * The product associated with this Redfish Service.
   * @return product
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The product associated with this Redfish Service.")

  public String getProduct() {
    return product;
  }




  public ServiceRootV1100ServiceRoot protocolFeaturesSupported(Object protocolFeaturesSupported) {
    
    this.protocolFeaturesSupported = protocolFeaturesSupported;
    return this;
  }

   /**
   * Get protocolFeaturesSupported
   * @return protocolFeaturesSupported
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getProtocolFeaturesSupported() {
    return protocolFeaturesSupported;
  }


  public void setProtocolFeaturesSupported(Object protocolFeaturesSupported) {
    this.protocolFeaturesSupported = protocolFeaturesSupported;
  }


   /**
   * The version of the Redfish Service.
   * @return redfishVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The version of the Redfish Service.")

  public String getRedfishVersion() {
    return redfishVersion;
  }




  public ServiceRootV1100ServiceRoot registries(Object registries) {
    
    this.registries = registries;
    return this;
  }

   /**
   * Get registries
   * @return registries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getRegistries() {
    return registries;
  }


  public void setRegistries(Object registries) {
    this.registries = registries;
  }


  public ServiceRootV1100ServiceRoot resourceBlocks(Object resourceBlocks) {
    
    this.resourceBlocks = resourceBlocks;
    return this;
  }

   /**
   * Get resourceBlocks
   * @return resourceBlocks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getResourceBlocks() {
    return resourceBlocks;
  }


  public void setResourceBlocks(Object resourceBlocks) {
    this.resourceBlocks = resourceBlocks;
  }


  public ServiceRootV1100ServiceRoot sessionService(Object sessionService) {
    
    this.sessionService = sessionService;
    return this;
  }

   /**
   * Get sessionService
   * @return sessionService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getSessionService() {
    return sessionService;
  }


  public void setSessionService(Object sessionService) {
    this.sessionService = sessionService;
  }


  public ServiceRootV1100ServiceRoot storage(Object storage) {
    
    this.storage = storage;
    return this;
  }

   /**
   * Get storage
   * @return storage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getStorage() {
    return storage;
  }


  public void setStorage(Object storage) {
    this.storage = storage;
  }


  public ServiceRootV1100ServiceRoot storageServices(Object storageServices) {
    
    this.storageServices = storageServices;
    return this;
  }

   /**
   * Get storageServices
   * @return storageServices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getStorageServices() {
    return storageServices;
  }


  public void setStorageServices(Object storageServices) {
    this.storageServices = storageServices;
  }


  public ServiceRootV1100ServiceRoot storageSystems(Object storageSystems) {
    
    this.storageSystems = storageSystems;
    return this;
  }

   /**
   * Get storageSystems
   * @return storageSystems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getStorageSystems() {
    return storageSystems;
  }


  public void setStorageSystems(Object storageSystems) {
    this.storageSystems = storageSystems;
  }


  public ServiceRootV1100ServiceRoot systems(Object systems) {
    
    this.systems = systems;
    return this;
  }

   /**
   * Get systems
   * @return systems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getSystems() {
    return systems;
  }


  public void setSystems(Object systems) {
    this.systems = systems;
  }


  public ServiceRootV1100ServiceRoot tasks(Object tasks) {
    
    this.tasks = tasks;
    return this;
  }

   /**
   * Get tasks
   * @return tasks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getTasks() {
    return tasks;
  }


  public void setTasks(Object tasks) {
    this.tasks = tasks;
  }


  public ServiceRootV1100ServiceRoot telemetryService(Object telemetryService) {
    
    this.telemetryService = telemetryService;
    return this;
  }

   /**
   * Get telemetryService
   * @return telemetryService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getTelemetryService() {
    return telemetryService;
  }


  public void setTelemetryService(Object telemetryService) {
    this.telemetryService = telemetryService;
  }


  public ServiceRootV1100ServiceRoot UUID(Object UUID) {
    
    this.UUID = UUID;
    return this;
  }

   /**
   * Get UUID
   * @return UUID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getUUID() {
    return UUID;
  }


  public void setUUID(Object UUID) {
    this.UUID = UUID;
  }


  public ServiceRootV1100ServiceRoot updateService(Object updateService) {
    
    this.updateService = updateService;
    return this;
  }

   /**
   * Get updateService
   * @return updateService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getUpdateService() {
    return updateService;
  }


  public void setUpdateService(Object updateService) {
    this.updateService = updateService;
  }


   /**
   * The vendor or manufacturer associated with this Redfish Service.
   * @return vendor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The vendor or manufacturer associated with this Redfish Service.")

  public String getVendor() {
    return vendor;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceRootV1100ServiceRoot serviceRootV1100ServiceRoot = (ServiceRootV1100ServiceRoot) o;
    return Objects.equals(this.atOdataContext, serviceRootV1100ServiceRoot.atOdataContext) &&
        Objects.equals(this.atOdataEtag, serviceRootV1100ServiceRoot.atOdataEtag) &&
        Objects.equals(this.atOdataId, serviceRootV1100ServiceRoot.atOdataId) &&
        Objects.equals(this.atOdataType, serviceRootV1100ServiceRoot.atOdataType) &&
        Objects.equals(this.accountService, serviceRootV1100ServiceRoot.accountService) &&
        Objects.equals(this.aggregationService, serviceRootV1100ServiceRoot.aggregationService) &&
        Objects.equals(this.certificateService, serviceRootV1100ServiceRoot.certificateService) &&
        Objects.equals(this.chassis, serviceRootV1100ServiceRoot.chassis) &&
        Objects.equals(this.compositionService, serviceRootV1100ServiceRoot.compositionService) &&
        Objects.equals(this.description, serviceRootV1100ServiceRoot.description) &&
        Objects.equals(this.eventService, serviceRootV1100ServiceRoot.eventService) &&
        Objects.equals(this.fabrics, serviceRootV1100ServiceRoot.fabrics) &&
        Objects.equals(this.facilities, serviceRootV1100ServiceRoot.facilities) &&
        Objects.equals(this.id, serviceRootV1100ServiceRoot.id) &&
        Objects.equals(this.jobService, serviceRootV1100ServiceRoot.jobService) &&
        Objects.equals(this.jsonSchemas, serviceRootV1100ServiceRoot.jsonSchemas) &&
        Objects.equals(this.links, serviceRootV1100ServiceRoot.links) &&
        Objects.equals(this.managers, serviceRootV1100ServiceRoot.managers) &&
        Objects.equals(this.nvMeDomains, serviceRootV1100ServiceRoot.nvMeDomains) &&
        Objects.equals(this.name, serviceRootV1100ServiceRoot.name) &&
        Objects.equals(this.oem, serviceRootV1100ServiceRoot.oem) &&
        Objects.equals(this.powerEquipment, serviceRootV1100ServiceRoot.powerEquipment) &&
        Objects.equals(this.product, serviceRootV1100ServiceRoot.product) &&
        Objects.equals(this.protocolFeaturesSupported, serviceRootV1100ServiceRoot.protocolFeaturesSupported) &&
        Objects.equals(this.redfishVersion, serviceRootV1100ServiceRoot.redfishVersion) &&
        Objects.equals(this.registries, serviceRootV1100ServiceRoot.registries) &&
        Objects.equals(this.resourceBlocks, serviceRootV1100ServiceRoot.resourceBlocks) &&
        Objects.equals(this.sessionService, serviceRootV1100ServiceRoot.sessionService) &&
        Objects.equals(this.storage, serviceRootV1100ServiceRoot.storage) &&
        Objects.equals(this.storageServices, serviceRootV1100ServiceRoot.storageServices) &&
        Objects.equals(this.storageSystems, serviceRootV1100ServiceRoot.storageSystems) &&
        Objects.equals(this.systems, serviceRootV1100ServiceRoot.systems) &&
        Objects.equals(this.tasks, serviceRootV1100ServiceRoot.tasks) &&
        Objects.equals(this.telemetryService, serviceRootV1100ServiceRoot.telemetryService) &&
        Objects.equals(this.UUID, serviceRootV1100ServiceRoot.UUID) &&
        Objects.equals(this.updateService, serviceRootV1100ServiceRoot.updateService) &&
        Objects.equals(this.vendor, serviceRootV1100ServiceRoot.vendor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atOdataContext, atOdataEtag, atOdataId, atOdataType, accountService, aggregationService, certificateService, chassis, compositionService, description, eventService, fabrics, facilities, id, jobService, jsonSchemas, links, managers, nvMeDomains, name, oem, powerEquipment, product, protocolFeaturesSupported, redfishVersion, registries, resourceBlocks, sessionService, storage, storageServices, storageSystems, systems, tasks, telemetryService, UUID, updateService, vendor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceRootV1100ServiceRoot {\n");
    sb.append("    atOdataContext: ").append(toIndentedString(atOdataContext)).append("\n");
    sb.append("    atOdataEtag: ").append(toIndentedString(atOdataEtag)).append("\n");
    sb.append("    atOdataId: ").append(toIndentedString(atOdataId)).append("\n");
    sb.append("    atOdataType: ").append(toIndentedString(atOdataType)).append("\n");
    sb.append("    accountService: ").append(toIndentedString(accountService)).append("\n");
    sb.append("    aggregationService: ").append(toIndentedString(aggregationService)).append("\n");
    sb.append("    certificateService: ").append(toIndentedString(certificateService)).append("\n");
    sb.append("    chassis: ").append(toIndentedString(chassis)).append("\n");
    sb.append("    compositionService: ").append(toIndentedString(compositionService)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    eventService: ").append(toIndentedString(eventService)).append("\n");
    sb.append("    fabrics: ").append(toIndentedString(fabrics)).append("\n");
    sb.append("    facilities: ").append(toIndentedString(facilities)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jobService: ").append(toIndentedString(jobService)).append("\n");
    sb.append("    jsonSchemas: ").append(toIndentedString(jsonSchemas)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    managers: ").append(toIndentedString(managers)).append("\n");
    sb.append("    nvMeDomains: ").append(toIndentedString(nvMeDomains)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    oem: ").append(toIndentedString(oem)).append("\n");
    sb.append("    powerEquipment: ").append(toIndentedString(powerEquipment)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    protocolFeaturesSupported: ").append(toIndentedString(protocolFeaturesSupported)).append("\n");
    sb.append("    redfishVersion: ").append(toIndentedString(redfishVersion)).append("\n");
    sb.append("    registries: ").append(toIndentedString(registries)).append("\n");
    sb.append("    resourceBlocks: ").append(toIndentedString(resourceBlocks)).append("\n");
    sb.append("    sessionService: ").append(toIndentedString(sessionService)).append("\n");
    sb.append("    storage: ").append(toIndentedString(storage)).append("\n");
    sb.append("    storageServices: ").append(toIndentedString(storageServices)).append("\n");
    sb.append("    storageSystems: ").append(toIndentedString(storageSystems)).append("\n");
    sb.append("    systems: ").append(toIndentedString(systems)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("    telemetryService: ").append(toIndentedString(telemetryService)).append("\n");
    sb.append("    UUID: ").append(toIndentedString(UUID)).append("\n");
    sb.append("    updateService: ").append(toIndentedString(updateService)).append("\n");
    sb.append("    vendor: ").append(toIndentedString(vendor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

